# Project-wide Gradle settings.
# IDE (e.g. Android Studio) users:
# IDE settings will override any values specified in this file.
# http://www.gradle.org/docs/current/userguide/build_environment.html

# AndroidX
android.useAndroidX=true

# JVM arguments for the Gradle daemon
org.gradle.jvmargs=-Xmx1536m

# Optional: enable parallel builds for multi-module projects
# org.gradle.parallel=true
